### ISSUE TITLE
Add Namespace element to all annotations.

### ISSUE THREAD

**Issue by jimk-osu** [ballerinax/kubernetes#119]
Any chance of having namespace added to all of the available annotations?

This could be handled downstream via CI, but having this in annotation would be optimal.

**Comment by lakwarus** [comment]
Thanks for the feedback! 

We will bring namespace support.  We can simply add namespace attribute to deployment annotation. But we need to think through and see how we can allow to override these environment specific values. One option might be passing these value via environment variable or ballerina toml.

**Comment by anuruddhal** [comment]
@jimk-osu: We will implement this with our composite application implementation.

**Comment by jimk-osu** [comment]
@anuruddhal Thanks for the info. 

Do you have an eta or roadmap of when composite apps will be available?

**Comment by anuruddhal** [comment]
@jimk-osu The timeline is not yet finalized yet. Until then we will add namespace support for deployment annotation.
