### ISSUE TITLE
Add support for pulling a docker image from a private docker registry

### ISSUE THREAD

**Issue by pubudu538** [ballerinax/kubernetes#147]
**Description:**
It would be great to have the feature which enables pulling the docker image from a private Docker registry.

https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by shikloshi** [comment]
+1

**Comment by anuruddhal** [comment]
Image pull secrets can be specified as 

```
@kubernetes:Deployment{
imagePullSecrets: ["mysecret1","mysecret2"]
}
```
