### ISSUE TITLE
Add imagePullSecrets to Deployment Annotation

### ISSUE THREAD

**Issue by jimk-osu** [ballerinax/kubernetes#159]
**Description:**
The current Deployment annotation supports username and password, but not imagePullSecrets.

Adding imagePullSecrets will enable use of existing secrets where applicable.

Per: https://ballerina.io/learn/api-docs/ballerinax/kubernetes.html#DeploymentConfiguration

**Suggested Labels:**
enhancement

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by anuruddhal** [comment]
This feature has been added with PR https://github.com/ballerinax/kubernetes/pull/157.
For issue https://github.com/ballerinax/kubernetes/issues/147.

**Comment by jimk-osu** [comment]
@anuruddhal Thanks for the reference! Should I pull the project and go the mvn route or is this baked into the nightly `Nightly 0.980.2-SNAPSHOT (Jul 31, 2018)`?

**Comment by anuruddhal** [comment]
It will be available on nightly build. 😊

**Comment by jimk-osu** [comment]
@anuruddhal you rock! 👍
