### ISSUE TITLE
Add Support for OpenShift

### ISSUE THREAD

**Issue by haarchri** [ballerinax/kubernetes#164]
hello, we also use OpenShift as an environment 

we need the following resources in ballerina - to enable a build and resources for OpenShift 

1.) function to disable Docker build - because we will build in OpenShift via BuildConfig
Show after Ballerina Build a message like:

> oc create -f *.yaml -n ${{NAMESPACE}}
> oc start-build ${{SERVICE_NAME}} --from-dir=. --follow=true

2.) create BuildConfig resource in Ballerina like:

generate the OpenShift BuildConfig as yaml:

> apiVersion: v1
> kind: BuildConfig
> metadata:
>   name: "{{$SERVICE_NAME}}"
>   labels:
>     app: "{{$SERVICE_NAME}}"
>     version: "latest"
> spec:
>   output:
>     to:
>       kind: ImageStreamTag
>       name: "{{$SERVICE_NAME}}:latest"
>   postCommit: {}
>   resources: {}
>   source:
>     binary: {}
>     secrets: null
>     type: Binary
>   strategy:
>     dockerStrategy:
>       forcePull: true
>       pullSecret:
>         name: builder-dockercfg-abcdef
>     type: Docker

3.) Create ImageStream Resource in Ballerina like:

Generate the OpenShift ImageStream as yaml:

> apiVersion: v1
> kind: List
> items:
> - apiVersion: v1
>   kind: ImageStream
>   metadata:
>     name: {{$SERVICE_NAME}}
>   spec:
>     lookupPolicy:
>       local: false
>     tags:
>     - annotations: null
>       from:
>         kind: DockerImage
>         name: docker-registry.default.svc:5000/{{$NAMESPACE}}/{{$SERVICE_NAME}}:latest
>       generation: null
>       importPolicy: {}
>       name: "latest"
>       referencePolicy:
>         type: ""
>   status:
>     dockerImageRepository: ""

4.) Create Route Resource in Ballerina like:

> @kubernetes:OpenShift:Route: {
>     host:"${{SERIVCE_NAME}}-${{NAMESPACE}}",
>     domain: "${{DOMAIN}}
> }

Generate the OpenShift Route as yaml:

> apiVersion: v1
> kind: Route
> metadata:
>   annotations:
>   labels:
>     app: ${{SERVICE_NAME}}
>   name: ${{SERVICE_NAME}}
> spec:
>   host: ${{SERVICE_NAME}}-${{NAMESPACE}}.${{DOMAIN}}
>   tls:
>   port:
>   to:
>     kind: Service
>     name: ${{SERVICE_NAME}}
>     weight: 100
>   wildcardPolicy: None

For all other resources like service, deployment is all fine for openshift

**Comment by anuruddhal** [comment]
@haarchri 
Docker build can be disabled by setting `buildImage` property to false in deployment annotation.

```ballerina
@kubernetes:Deployment{
     buildImage: false
}
```
Supporting openshift resources are not yet implemented.
