### ISSUE TITLE
Use Finite Types for Annotation Enum Values

### ISSUE THREAD

**Issue by lafernando** [ballerinax/kubernetes#209]
In the current Kubernetes and related plugins, in places such as https://ballerina.io/learn/api-docs/ballerinax/kubernetes.html#ServiceConfiguration - imagePullPolicy, these fields are just string types, and doesn't give an indication of the supported values. These must be declared as an infinite type, such as: type ImagePullPolicy "PullIfNotPresent"|"Foo"|"Bar". So this will make the documentation far more clear for users.

**Comment by hemikak** [comment]
We have to wait for compile time constants for this. As we are building the artifacts during compilation.
