### ISSUE TITLE
Add Tolerations to DeploymentConfig

### ISSUE THREAD

**Issue by jimk-osu** [ballerinax/kubernetes#335]
**Description:**
Please add [tolerations](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#toleration-v1-core) to [DeploymentConfiguration](https://ballerina.io/learn/api-docs/ballerinax/kubernetes.html#DeploymentConfiguration) to enable deployment of ballerina services to tainted nodes.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by jimk-osu** [comment]
@lakwarus Please let me know more info is needed! 😄

**Comment by lakwarus** [comment]
@jimk-osu this is fine. thanks
