### ISSUE TITLE
DeploymentConfig - namespace not accepting config string

### ISSUE THREAD

**Issue by jimk-osu** [ballerinax/kubernetes#336]
**Description:**
We're trying to make the some of the DeploymentConfiguration values be driven by `ballerina/config` parameters.

I'm getting the following error when I try to run:
```
error: .::somebal.bal:127:1: unable to parse value: config:getAsString(kube.namespace)
```
With explicit type casting I get the same:

```
error: .::student-info.bal:127:1: unable to parse value: <string> config:getAsString(kube.namespace)
```

`ballerina.conf`:
```
[kube]
namespace="bal"
imagePullSecret="regcred"
```

DeploymentConfiguration:
```ballerina
@kubernetes:Deployment {
    image: "somerepo:5000/ballerina/sombal:v1.2",
    name: "somebal",
    namespace: config:getAsString("kube.namespace"),
    replicas: 2,
    imagePullSecrets: [config:getAsString("kube.imagePullSecret")],
    livenessProbe: true, 
    singleYAML: false,
    copyFiles:[
        {
            target:"/ballerina/runtime/bre/lib",
            source:"./conf/ojdbc7.jar"
        }
    ]
}
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
`Ballerina 0.991.0`
**OS, DB, other environment details and versions:**    
`Darwin`
**Steps to reproduce:**

**Related Issues:**

**Comment by Manuri** [comment]
config API can be used during runtime of a Ballerina program whereas these k8s annotations are processed during build time. This is the expected behavior. 

However, you can read environmental variables inside the deployment annotation similar to [this](https://github.com/ballerinax/kubernetes/blob/v0.991.0/samples/sample6/hello_world_gce.bal#L15).

**Comment by hemikak** [comment]
Please reopen if issue exists. I have updated the README.md on how to use environment variables for annotation field values.
