### ISSUE TITLE
We cannot put username/password in code

### ISSUE THREAD

**Issue by pzfreo** [ballerinax/kubernetes#37]
**Description:**
It is not acceptable to have docker username/password in any program code.

Can we not use the local docker instance to push on our behalf? Most users have already logged into docker locally and this can be a prerequisite for the build. Alternatively, there could be some credential file stored locally or some secrets managed by ballerina.

**Suggested Labels:**
security

**Suggested Assignees:**

**Affected Product Version:**
All

**OS, DB, other environment details and versions:**    
All

**Steps to reproduce:**

**Related Issues:**

**Comment by lakwarus** [comment]
Hi Paul,

we are thinking two option here. Already created issue for one option in docker support [1].  Second option is to put variable name for username and password, which can be resolved from env variable or toml file.

[1] https://github.com/ballerinax/docker/issues/9

**Comment by anuruddhal** [comment]
Now the username and password(or any attribute) can be resolved using environment variables using $env{} syntaxes.

```
@kubernetes:Deployment{
    enableLiveness:"enable",
    push:true,
    image:"index.docker.io/$env{DOCKER_USERNAME}/gce-sample:1.0",
    username:"$env{DOCKER_USERNAME}",
    password:"$env{DOCKER_PASSWORD}"
}
```
