### ISSUE TITLE
ConfigMaps does not work relative path

### ISSUE THREAD

**Issue by hemikak** [ballerinax/kubernetes#447]
**Description:**
Configmaps does not work when relative path with given with leading `./`
Example:
```ballerina
@kubernetes:ConfigMap {
    conf: "./cool_drink/ballerina.conf"
}
```

**Affected Product Version:**
Ballerina 1.1.0

**OS, DB, other environment details and versions:**  
Mac

**Comment by anuruddhal** [comment]
Reolved with https://github.com/ballerinax/kubernetes/pull/386/files
